version: 1.2.0
services:
  - php:
     version: 7.2
variables:
  global:
    PIPELINE_JOB_URL: "https://cloud.acquia.com/app/develop/applications/${PIPELINE_APPLICATION_ID}/pipelines/jobs/${PIPELINE_JOB_ID}"
events:
  build:
    steps:
      - welcome:
          script:
            - echo 'Hello World at 17th May 2019!'
            - php -v
