version: 1.2.0
services:
  - mysql
variables:
  global:
    PIPELINE_JOB_URL: "https://cloud.acquia.com/app/develop/applications/${PIPELINE_APPLICATION_ID}/pipelines/jobs/${PIPELINE_JOB_ID}"
events:
  build:
    steps:
      - welcome:
          script:
            - echo 'Hello World!'
            - echo $PIPELINE_JOB_URL
            - echo 'Job completed, August 17th 2018 :P'
            - whoami
            - cat /etc/os-release
            - mysql -u root -proot -e "show variables like '%timeout'"
            - mysql -u root -proot -e "show variables like '%max_allowed_packet'"
            - mysql -u root -proot -e "show variables like '%innodb_log_file_size'"
