version: 1.2.0
services:
  - php
events:
  build:
    steps:
      - welcome:
          script: 
            - kernel=$([ "$(cat /proc/sys/crypto/fips_enabled)" == 1 ] && echo "fips" || echo "not fips")
            - echo "Kernel is $kernel enabled."
            - openssl_var=$([ "$OPENSSL_FIPS" == 1 ] && echo "set" || echo "not set")
            - echo "OpenSSL_FIPS env var is $openssl_var to 1."
            - openssl md5 ./welcome.txt || echo 'OpenSSL md5 is not supported in FIPS mode.'
            - node -e "require('crypto').createHash('md5').update('')" || echo 'Node md5 is not supported in FIPS mode.' 
            - php -r 'echo md5("foo");' || 'PHP md5 is not working.'
