version: 1.0.0

services:
  - mysql
  - php:
      version: 7.3
  
events:
  build:
    steps:
      # If you have build instructions, put them here. They are not required.
      - build_site:
          script:
            - echo 'HW!'
            - php -v
            - mysql --version


